webtalk_init -webtalk_dir /home/user/Documents/VHDL_Bowling/Final_Project.sim/sim_1/behav/xsim/xsim.dir/bowling_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 25 15:05:36 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c67299ac-72aa-49e1-b744-f538ecb3e72b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9bec0c295b104bc78435ec695854aefc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "102" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "50511140 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "12.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "127312_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1706156374 -regid "" -xml /home/user/Documents/VHDL_Bowling/Final_Project.sim/sim_1/behav/xsim/xsim.dir/bowling_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/user/Documents/VHDL_Bowling/Final_Project.sim/sim_1/behav/xsim/xsim.dir/bowling_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/user/Documents/VHDL_Bowling/Final_Project.sim/sim_1/behav/xsim/xsim.dir/bowling_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
