webtalk_init -webtalk_dir C:/Users/moham/Documents/Final_Project/Final_Project.sim/sim_1/behav/xsim/xsim.dir/bowling_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 24 19:31:56 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1a836f17-7070-4c27-bfce-7a495a88497f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9bec0c295b104bc78435ec695854aefc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "101" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "45.36_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "17676_KB" -context "xsim\\usage"
webtalk_transmit -clientid 94881541 -regid "" -xml C:/Users/moham/Documents/Final_Project/Final_Project.sim/sim_1/behav/xsim/xsim.dir/bowling_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/moham/Documents/Final_Project/Final_Project.sim/sim_1/behav/xsim/xsim.dir/bowling_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/moham/Documents/Final_Project/Final_Project.sim/sim_1/behav/xsim/xsim.dir/bowling_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
