#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Apr 25 15:05:07 EDT 2023
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 9bec0c295b104bc78435ec695854aefc --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot bowling_tb_behav xil_defaultlib.bowling_tb -log elaborate.log"
xelab -wto 9bec0c295b104bc78435ec695854aefc --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot bowling_tb_behav xil_defaultlib.bowling_tb -log elaborate.log

